#!/usr/bin/env node
/**
 * ACG Paper Auto-Index — HTML generator
 *
 * Renders papers.json into guild/web/dist/white-papers.html using the
 * paper-card template defined in the Paper Auto-Index Standard.
 */
const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const PAPERS_JSON = path.join(REPO_ROOT, 'papers.json');
const OUT = path.join(REPO_ROOT, 'guild', 'web', 'dist', 'white-papers.html');

const TYPE_LABELS = {
  'white-paper':    'White Paper',
  'position-paper': 'Position Paper',
  'experimental':   'Experimental',
  'research-note':  'Research Note',
  'knowledge':      'Knowledge About Knowledge',
  'standard':       'Standard',
};

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function formatDate(iso) {
  const m = /^(\d{4})-(\d{2})-\d{2}$/.exec(iso);
  if (!m) return esc(iso);
  return `${MONTHS[parseInt(m[2], 10) - 1]} ${m[1]}`;
}

function renderCard(p) {
  const typeLabel = TYPE_LABELS[p.type] || p.type;
  const tagsAttr = (p.tags || []).join(' ');
  const tagBadges = (p.tags || [])
    .map(t => `<span class="tag">${esc(t)}</span>`)
    .join(' ');
  const statusBadge = (p.status === 'draft' || p.status === 'review')
    ? `<span class="paper-status-badge">${esc(p.status.charAt(0).toUpperCase() + p.status.slice(1))}</span>`
    : '';

  return `<article class="paper-card" data-type="${esc(p.type)}" data-tags="${esc(tagsAttr)}">
    <div class="paper-meta">
        <span class="paper-author">${esc(p.author)}</span>
        <span class="paper-date">${formatDate(p.date)}</span>
        <span class="paper-id">${esc(p.id)}</span>
    </div>
    <div class="paper-type-badge">${esc(typeLabel)}</div>${statusBadge}
    <h3>${esc(p.title)}</h3>
    <p class="paper-abstract">${esc(p.abstract)}</p>
    <div class="paper-tags">${tagBadges}</div>
    <a href="${esc(p.source_file || p.slug + '.html')}" class="paper-link">Read ${esc(typeLabel)} →</a>
</article>`;
}

function main() {
  if (!fs.existsSync(PAPERS_JSON)) {
    console.error('[generate-html] papers.json not found — run parse-papers.js first');
    process.exit(1);
  }
  const papers = JSON.parse(fs.readFileSync(PAPERS_JSON, 'utf8'));

  // Group by type label
  const groups = {};
  for (const p of papers) {
    const label = TYPE_LABELS[p.type] || p.type;
    (groups[label] = groups[label] || []).push(p);
  }

  let sections = '';
  for (const label of Object.keys(TYPE_LABELS).map(k => TYPE_LABELS[k])) {
    if (!groups[label]) continue;
    const cards = groups[label].map(renderCard).join('\n\n');
    sections += `
<section class="papers-shell">
    <div class="section-heading">
        <h2>${esc(label)}s</h2>
        <p>${groups[label].length} publication${groups[label].length === 1 ? '' : 's'}.</p>
    </div>
    <div class="papers-grid">
${cards}
    </div>
</section>
`;
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>White Papers - AI Craftspeople Guild</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&amp;family=Work+Sans:wght@300;400;600&amp;family=Courier+Prime:wght@400;700&amp;display=swap" rel="stylesheet">
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-Z1CEF69ZSH"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-Z1CEF69ZSH');
    </script>
    <link rel="stylesheet" href="../style/main.css">
</head>
<body class="page-white-papers">
    <header>
        <div class="guild-mark"><div class="emblem">⚒ ACG ⚒</div></div>
        <h1>White Papers</h1>
        <p class="subtitle">Guild publications generated by the Paper Auto-Index pipeline.</p>
        <div class="back-link"><a href="../../../index.html">← Back to Home</a></div>
    </header>

    <main class="container">
        <section class="intro-panel">
            <p>This page is auto-generated from <code>papers.json</code> on every PR via
            the <a href="../../../docs/engineering/standards/paper-auto-index.md">Paper Auto-Index Standard</a>.
            ${papers.length} publications indexed.</p>
        </section>
${sections}
    </main>

    <footer>
        <p>© 2026 AI Craftspeople Guild.</p>
        <p><a href="https://github.com/aicraftspeopleguild">GitHub</a></p>
    </footer>
</body>
</html>
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, html, 'utf8');
  console.log(`[generate-html] wrote ${path.relative(REPO_ROOT, OUT)} (${papers.length} papers)`);
}

if (require.main === module) {
  try { main(); } catch (e) { console.error(e); process.exit(1); }
}

module.exports = { main };
