// ── ACG paper-apps · landing renderer ──────────────────────
// Reads the same papers.json the Android umbrella bundles, renders
// a card grid, links into paper.html?slug=<id>. Every paper is a
// PaperApp UDT instance upstream — this is the web projection.

const $ = s => document.querySelector(s);

async function main() {
  let papers;
  try {
    papers = await fetch('./papers.json', { cache: 'no-store' }).then(r => r.json());
  } catch (e) {
    $('#grid').innerHTML = `<p class="err">could not load papers.json: ${e.message}</p>`;
    return;
  }
  $('#meta').textContent =
    `${papers.length} papers · generated by phone/whitepapers/_generator/build-umbrella.py`;

  const minis = await loadMiniMap();

  const frag = document.createDocumentFragment();
  for (const p of papers) {
    const card = document.createElement('a');
    card.className = 'card';
    card.href = `./paper.html?slug=${encodeURIComponent(p.slug)}`;
    card.style.setProperty('--accent', p.theme_color_hex || '#1a5c4c');
    card.innerHTML = `
      <span class="stripe"></span>
      ${p.doc_number ? `<div class="doc">${esc(p.doc_number)}</div>` : '<div class="doc" style="opacity:0.4">—</div>'}
      <div class="title">${esc(p.title)}</div>
      <div class="byline">${esc(by(p))}</div>
      ${p.abstract ? `<div class="abs">${esc(p.abstract)}</div>` : ''}
      <div class="mini">${minis[p.slug] ? `try · <b>${esc(minis[p.slug])}</b>` : 'paper · read'}</div>
    `;
    frag.appendChild(card);
  }
  $('#grid').innerHTML = '';
  $('#grid').appendChild(frag);
}

async function loadMiniMap() {
  // Per-paper mini blurbs (what the Try tab does). Inline here —
  // could be pulled from a separate JSON later.
  return {
    'flywheel':                                   'cycle logger · streak',
    'you-re-absolutely-wrong':                    'certainty reversal log',
    'ai-that-pisses-you-off-the-surprisingly':    'pushback dial 0→100',
    'acg-kcc-guild-chain':                        'guild-coin ledger',
    'acg-net-decentralized-guild-web':            'mesh visualizer',
    'lightning-factory':                          '7.83 Hz pulse',
    'the-dog-the-data-scientist-and-the-mrna':    'Bayes pocketbook',
    'the-harm-equation':                          'sev × reach × (1-rev)',
    'the-konomi-standard':                        'UDT JSON validator',
    'the-prediction-trap':                        'calibration logger',
    'ass-os-bloom-prompt-the-irrational':         'irrational prompt deck',
    'ass-os-bloom-prompt-the-rational-empire':    'rational prompt deck',
    'the-shield-of-all-knights-against':          'bias flashcards',
    'from-correctness-to-integrity-measuring':    'code-integrity inspector',
    'avoid-being-fractally-wrong':                'Sierpinski depth demo',
    'the-pattern-that-wasn-t-there':              'pareidolia game',
    'ai-harness-constraint-driven-software':      'constraint ledger',
    'convergent-governance-topologies-in':        'governance classifier',
    'toastmasters-scrapers-guild':                'URL auditor',
    'acg-review-forge':                           'copy-to-clipboard prompts',
    'grid-brain':                                 'Game of Life 18×18',
    's-a-d':                                      '30-day mood sparkline',
    'structural-toast-carbonization-a-failure':   'toast-ageing clock',
    'i-ll-burn-toast-and-you-scrape-it-a':        'burner / scraper quiz',
    'ass-os-bloom-prompt-occam':                  'verbosity filter',
  };
}

const by = p => [p.author, p.date].filter(Boolean).join(' · ');
const esc = s => String(s ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');

main();
