package com.aicraftspeopleguild.acg.papers

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.graphics.toColorInt

/**
 * One-screen paper app. Shows title / author / date / doc number /
 * abstract plus a button to open the full paper in the browser.
 * Generated by phone/whitepapers/_generator/build.py from the
 * WhitepaperApp UDT instance at L3/udts/whitepaper-app/instances/flywheel.json.
 */
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { PaperApp() }
    }
}

@Composable
private fun PaperApp() {
    val primary = remember_color("#1A5C4C")
    val scheme = androidx.compose.material3.darkColorScheme(
        primary      = primary,
        onPrimary    = Color(0xFFFAF6F0),
        background   = Color(0xFF0D1117),
        onBackground = Color(0xFFE6EDF3),
        surface      = Color(0xFF161B22),
        onSurface    = Color(0xFFE6EDF3),
    )
    MaterialTheme(colorScheme = scheme) {
        val ctx = LocalContext.current
        Surface(color = MaterialTheme.colorScheme.background) {
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .verticalScroll(rememberScrollState())
                    .padding(24.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp),
            ) {
                Text(
                    "ACG-WP-FLYWHEEL",
                    fontFamily = FontFamily.Monospace,
                    color = MaterialTheme.colorScheme.primary,
                    fontSize = 11.sp,
                    letterSpacing = 2.sp,
                    fontWeight = FontWeight.Bold,
                )
                Text(
                    "The Flywheel",
                    fontSize = 28.sp,
                    fontWeight = FontWeight.Bold,
                    lineHeight = 34.sp,
                )
                Text(
                    "AI Craftspeople Guild  ·  2026",
                    color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.7f),
                    fontSize = 13.sp,
                )
                HorizontalDivider()
                Text(
                    "Compounding returns from craft · a small loop that builds on itself every cycle — write, ship, review, teach, write — and why that loop is the only one that grows without burning its operators out.",
                    fontSize = 15.sp,
                    lineHeight = 22.sp,
                    color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.88f),
                )
                Spacer(Modifier.height(12.dp))
                Button(
                    onClick = {
                        ctx.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("https://teslasolar.github.io/aicraftspeopleguild.github.io/#/whitepapers/flywheel")))
                    },
                    modifier = Modifier.align(Alignment.Start),
                ) { Text("Read the full paper ↗") }
                Spacer(Modifier.height(16.dp))
                Text(
                    "part of the ACG whitepaper library  ·  aicraftspeopleguild.github.io",
                    fontSize = 10.sp,
                    color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.4f),
                )
            }
        }
    }
}

@Composable
private fun remember_color(hex: String): Color {
    // Accepts "#RRGGBB" or "#AARRGGBB". Falls back to the primary
    // charter green if the hex string is somehow malformed.
    return try { Color(hex.toColorInt()) } catch (_: Throwable) { Color(0xFF1A5C4C) }
}
