package {{ANDROID_PACKAGE}}

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.graphics.toColorInt

/**
 * One-screen paper app. All paper text flows through strings.xml so
 * titles with inner quotes / & / < render cleanly without needing
 * per-paper Kotlin escaping. Theme color comes in via a string
 * resource too so the generator never touches Kotlin content.
 * Generated by phone/whitepapers/_generator/build.py from the
 * WhitepaperApp UDT instance at
 * L3/udts/whitepaper-app/instances/<slug>.json.
 */
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { PaperApp() }
    }
}

@Composable
private fun PaperApp() {
    val primary = rememberThemeColor(stringResource(R.string.theme_color_hex))
    val scheme = androidx.compose.material3.darkColorScheme(
        primary      = primary,
        onPrimary    = Color(0xFFFAF6F0),
        background   = Color(0xFF0D1117),
        onBackground = Color(0xFFE6EDF3),
        surface      = Color(0xFF161B22),
        onSurface    = Color(0xFFE6EDF3),
    )
    MaterialTheme(colorScheme = scheme) {
        val ctx = LocalContext.current
        val paperUrl = stringResource(R.string.paper_url)
        Surface(color = MaterialTheme.colorScheme.background) {
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .verticalScroll(rememberScrollState())
                    .padding(24.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp),
            ) {
                val doc = stringResource(R.string.paper_doc_number)
                if (doc.isNotBlank()) {
                    Text(
                        doc,
                        fontFamily = FontFamily.Monospace,
                        color = MaterialTheme.colorScheme.primary,
                        fontSize = 11.sp,
                        letterSpacing = 2.sp,
                        fontWeight = FontWeight.Bold,
                    )
                }
                Text(
                    stringResource(R.string.paper_title),
                    fontSize = 28.sp,
                    fontWeight = FontWeight.Bold,
                    lineHeight = 34.sp,
                )
                val byline = listOf(
                    stringResource(R.string.paper_author),
                    stringResource(R.string.paper_date),
                ).filter { it.isNotBlank() }.joinToString("  ·  ")
                if (byline.isNotBlank()) {
                    Text(
                        byline,
                        color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.7f),
                        fontSize = 13.sp,
                    )
                }
                HorizontalDivider()
                val abstract = stringResource(R.string.paper_abstract)
                if (abstract.isNotBlank()) {
                    Text(
                        abstract,
                        fontSize = 15.sp,
                        lineHeight = 22.sp,
                        color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.88f),
                    )
                }
                Spacer(Modifier.height(12.dp))
                Button(
                    onClick = { ctx.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(paperUrl))) },
                    modifier = Modifier.align(Alignment.Start),
                ) { Text("Read the full paper ↗") }
                Spacer(Modifier.height(16.dp))
                Text(
                    "part of the ACG whitepaper library  ·  aicraftspeopleguild.github.io",
                    fontSize = 10.sp,
                    color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.4f),
                )
            }
        }
    }
}

@Composable
private fun rememberThemeColor(hex: String): Color = remember(hex) {
    try { Color(hex.toColorInt()) } catch (_: Throwable) { Color(0xFF1A5C4C) }
}
