// ═══ MCP · scaffolds ═══
// Preset starter projects. A scaffold writes a handful of files into
// the VFS (never overwrites unless the repo is empty) and returns the
// entry file so the operator can preview it immediately.

import {repo,publish} from './repo.js';
import {createFile,editFile} from './vfs.js';

const STARTERS={
  vanilla:{
    entry:'/index.html',
    files:{
      '/index.html':
`<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>Hello ACG</title>
<link rel="stylesheet" href="style.css">
</head><body>
<h1 id="greet">Hello, mesh!</h1>
<button id="beat">Beat</button>
<p id="out"></p>
<script src="app.js"></script>
</body></html>
`,
      '/style.css':
`*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,sans-serif;padding:40px;background:#faf6f0;color:#1a2332}
h1{font-size:28px;margin-bottom:16px;color:#1a5c4c}
button{padding:8px 18px;border:1px solid #1a5c4c;background:#1a5c4c;color:#fff;border-radius:6px;cursor:pointer}
`,
      '/app.js':
`let n=0;
document.getElementById('beat').onclick = () => {
  n++;
  document.getElementById('out').textContent = 'beats: '+n;
};
`,
    },
  },

  spa:{
    entry:'/index.html',
    files:{
      '/index.html':
`<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>SPA · ACG</title>
<link rel="stylesheet" href="style.css">
</head><body>
<nav><a href="#/">home</a> · <a href="#/about">about</a></nav>
<main id="view"></main>
<script src="router.js"></script>
<script src="app.js"></script>
</body></html>
`,
      '/style.css':
`body{font-family:system-ui,sans-serif;margin:0;padding:24px;background:#faf6f0;color:#1a2332}
nav{padding-bottom:10px;border-bottom:1px solid #ccc;margin-bottom:16px}
nav a{margin-right:8px;color:#1a5c4c;text-decoration:none;font-weight:600}
`,
      '/router.js':
`const routes={};
export function route(path,fn){routes[path]=fn}
export function render(){
  const h=(location.hash||'#/').slice(1);
  const fn=routes[h]||routes['/'];
  const v=document.getElementById('view');
  if(v&&fn)v.innerHTML=fn();
}
window.addEventListener('hashchange',render);
window.addEventListener('load',render);
`,
      '/app.js':
`import {route,render} from './router.js';
route('/',     () => '<h1>Home</h1><p>Hello ACG.</p>');
route('/about',() => '<h1>About</h1><p>Scaffold generated by the MCP tool engine.</p>');
render();
`,
    },
  },

  markdown:{
    entry:'/index.html',
    files:{
      '/index.html':
`<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>Notes · ACG</title>
<link rel="stylesheet" href="style.css">
</head><body>
<article id="doc"></article>
<script src="app.js"></script>
</body></html>
`,
      '/README.md':
`# Notes

- Edit me at /README.md.
- Re-preview /index.html to see the render.
- The renderer is a 30-line Markdown subset.
`,
      '/style.css':
`body{font-family:system-ui,sans-serif;max-width:720px;margin:0 auto;padding:30px;background:#faf6f0;color:#1a2332;line-height:1.6}
h1,h2,h3{font-family:serif;color:#1a5c4c;margin:20px 0 8px}
code{background:#eee;padding:1px 5px;border-radius:3px;font-family:ui-monospace,monospace;font-size:0.9em}
pre{background:#1c2128;color:#c9d1d9;padding:12px;border-radius:6px;overflow:auto}
`,
      '/app.js':
`async function load(){
  const r = await fetch('README.md');
  const src = await r.text();
  document.getElementById('doc').innerHTML = render(src);
}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;')}
function render(md){
  return md.split(/\\n\\n+/).map(b=>{
    if(b.startsWith('### ')) return '<h3>'+esc(b.slice(4))+'</h3>';
    if(b.startsWith('## '))  return '<h2>'+esc(b.slice(3))+'</h2>';
    if(b.startsWith('# '))   return '<h1>'+esc(b.slice(2))+'</h1>';
    if(b.startsWith('\`\`\`')) return '<pre><code>'+esc(b.replace(/^\`\`\`\\w*\\n?|\`\`\`$/g,''))+'</code></pre>';
    if(/^- /m.test(b))       return '<ul>'+b.split(/\\n/).filter(l=>l.startsWith('- ')).map(l=>'<li>'+esc(l.slice(2))+'</li>').join('')+'</ul>';
    return '<p>'+esc(b).replace(/\`([^\`]+)\`/g,'<code>$1</code>')+'</p>';
  }).join('\\n');
}
load();
`,
    },
  },

  canvas:{
    entry:'/index.html',
    files:{
      '/index.html':
`<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>Canvas · ACG</title>
<link rel="stylesheet" href="style.css">
</head><body>
<canvas id="cv" width="640" height="400"></canvas>
<script src="app.js"></script>
</body></html>
`,
      '/style.css':
`body{margin:0;background:#1c2128;display:grid;place-items:center;min-height:100vh}
canvas{background:#faf6f0;border-radius:8px;box-shadow:0 8px 24px rgba(0,0,0,.4)}
`,
      '/app.js':
`const cv=document.getElementById('cv'),ctx=cv.getContext('2d');
let t=0;
function frame(){
  t+=0.02;
  ctx.clearRect(0,0,cv.width,cv.height);
  for(let i=0;i<40;i++){
    const x=cv.width/2+Math.cos(t+i*0.16)*160;
    const y=cv.height/2+Math.sin(t*1.3+i*0.24)*120;
    ctx.fillStyle='hsl('+((i*9+t*60)%360)+' 60% 50%)';
    ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill();
  }
  requestAnimationFrame(frame);
}
frame();
`,
    },
  },
};

export function scaffold(kind='vanilla'){
  const starter=STARTERS[kind];
  if(!starter)return{ok:false,error:'unknown scaffold: '+kind+' · try vanilla|spa|markdown|canvas'};
  const touched=[];
  for(const[path,content]of Object.entries(starter.files)){
    if(repo.files.has(path)){
      editFile(path,content);
    }else{
      createFile(path,content);
    }
    touched.push(path);
  }
  publish('scaffold',{kind,files:touched.length,entry:starter.entry});
  return{ok:true,kind,files:touched,entry:starter.entry};
}

export const SCAFFOLD_KINDS=Object.keys(STARTERS);
